#!/bin/sh

# Grabs all of the .so files generated by cargo.
# Takes one argument specifying whether or not it should look
# in the "release" or "debug" folder.

find cargo_rust_from_c/target/$1/*.so
# The file extension could be "so", "dylib", or "dll" depending on the platform.
